### ISSUE TITLE
Provision of backup and restore services for GeoNode

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-geosafe#121]
Add well-documented backup services to our standard Rancher orchestration for GeoNode. 

Try to use, build on or integrate with existing functionality or at least discuss with Alessio Fabiano and the GeoNode community about the
existing backup and restore functionality as described in http://docs.geonode.org/en/master/tutorials/admin/backup_restore to ensure that the solution fits in to GeoNode’s roadmap.

Set up a backup host at INGC and provide instruction on how to manage backups.

child of https://github.com/kartoza/geonode/issues/458

**Comment by lucernae** [comment]
@gubuntu If we use this, we might have to leave Kartoza's Hanoi backups. They already has a nice admin interface for this.

**Comment by gubuntu** [comment]
I think we should use this and if our tools add anything, then if there's time we can extend or improve GeoNode's tooling with ours. 

So I recommend getting GeoNode's 'native' backup implementation into our orchestration and deployed on testing asap, unless you think there's too much refactoring to do...?

**Comment by lucernae** [comment]
Regarding this.

I consider at this point (branch source: 2.8.x), GeoNode's native backup implementation is too buggy.
I implemented some fixes from lessons on what I learned when helping @dimasciput implement GeoNode's backup restore for GeoServer backend.

Some possible problem:

1. GeoNode uses fixtures dump to save the database models. One of the downside is, it's not a snapshot of the database. When the fixtures are loaded, there might be some models which is not dumped in the fixtures. Also the migration information is lost. So we can't use this approach when upgrading GeoNode major version. But it seems to be okay for day-to-day backups
2. The Admin panel is buggy because of limitations. When you are trying to create a backup from the Admin panel, you create a `backup` object then you execute the backup procedure. When the procedure is done, you got the file location of the backup, then you saved the location to that backup django model. However when you do a restore, the django model didn't contain the location info (because obviously, it's not created yet). So, after a sucessful restore, you will have a backup entry with empty location field, even though the backup exists and the restore is successful.
3. It's hard to override the backup procedure. Even so, it's not impossible, it's just not pretty. For example, in GeoSAFE, the backup procedure have name `backup_geosafe` because we can't use the same name `backup` command with the original GeoNode, because GeoSAFE app comes last in `INSTALLED_APPS` list, and is actually overridden by original GeoNode command.

Regardless of the issue above, I implemented the behaviour as good as possible. We can use GeoNode backup/restore management command now as well as from the Admin panel interface.

**Comment by gubuntu** [comment]
Awesome @lucernae. Your rich feedback on various issues needs to get into the docs...I'll to to ensure that. And upstream should take note too (which they will when we push)

**Comment by lucernae** [comment]
To reiterate my point, for the management command use:

```
python manage.py backup
```

and 

```
python manage.py restore
```

Respectively for GeoNode backup/restore. It will switch to current backend implementation.

However, for GeoSAFE, because I can't override it, use:

```
python manage.py backup_geosafe
```

and 

```
python manage.py restore_geosafe
```

**Comment by NyakudyaA** [comment]
Tested backups from the management commands and it all works properly. both for GeoSAFE and Geonode

Don't have an instance to test the restore from.

**Comment by NyakudyaA** [comment]
WIll close this and we can open if someone experiences problems with the restore. tested the backups and they work.
